name: Raw API

on:
    push:
        branches: [main]
        paths:
            - ".github/workflows/main.yml"
            - "index.js"

    schedule:
        - cron: "*/15 * * * *"

    workflow_dispatch:

jobs:
    update:
        name: Update
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - uses: actions/checkout@v4
              with:
                  repository: is-a-dev/register
                  path: is-a-dev

            - uses: actions/setup-node@v4
              with:
                  node-version: 22

            - name: Update Data
              run: node index.js

            - name: Commit
              run: |
                  git config --global user.email "bot@williamharrison.dev"
                  git config --global user.name "WDH-Bot"
                  git add index.json
                  git commit -m "Update Data"
                  git push
