name: Data

on:
    push:
        branches: [main]
        paths:
            - ".github/workflows/main.yml"
            - "scripts/*"

    schedule:
        - cron: "0 * * * *"

    workflow_dispatch:

jobs:
    update:
        name: Update
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3

            - uses: actions/checkout@v3
              with:
                  repository: is-a-dev/register
                  path: main

            - uses: actions/setup-node@v2
              with:
                  node-version: 16

            - name: Run Script
              run: node scripts/update.js

            - name: Commit
              run: |
                  git config --global user.email "bot@williamharrison.dev"
                  git config --global user.name "WDH-Bot"
                  git add index.json
                  git commit -m "Update Data"
                  git push
