name: Raw API

on:
    push:
        branches: [main]
        paths:
            - ".github/workflows/main.yml"
            - "index.mjs"

    schedule:
        - cron: "*/30 * * * *"

    workflow_dispatch:

jobs:
    update:
        name: Update
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3

            - uses: actions/checkout@v3
              with:
                  repository: is-a-dev/register
                  path: is-a-dev

            - uses: actions/setup-node@v2
              with:
                  node-version: 16

            - run: npm install

            - name: Update Data
              run: node --experimental-modules index.mjs

            - name: Commit
              run: |
                  git config --global user.email "bot@williamharrison.dev"
                  git config --global user.name "WDH-Bot"
                  git add index.json
                  git commit -m "Update Data"
                  git push
